name: Run rspec, rubocop

on:
  push:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}

jobs:
  rubocop:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - run: |
          gh pr diff ${{ github.event.number }} --name-only |
          xargs -I {} sh -c '[ -f "{}" ] && echo "{}"' |
          xargs --no-run-if-empty bundle exec rubocop --force-exclusion
