name: Run rspec, rubocop

on:
  push:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}

jobs:
  rubocop:
    steps:
      - run: |
          gh pr diff ${{ github.event.number }} --name-only |
          xargs -I {} sh -c '[ -f "{}" ] && echo "{}"' |
          xargs --no-run-if-empty bundle exec rubocop --force-exclusion
