name: Run rspec, rubocop

on:
  push:
  pull_request:

jobs:
  rubocop:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - run: bundle exec rubocop
