name: Run rspec, rubocop

on:
  push:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: install rubocop
        run: gem install rubocop

      - name: bundle update --conservative net-pop
        run: bundle update net-pop

      - name: bundle install
        run: bundle install

      - name: Run rubocop
        run: rubocop
