name: Run rspec, rubocop
on:
  push:
  pull_request:

jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Ruby Env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
        bundler-cache: true
      - name: rubocop
        run: bundle exec rubocop
